### PR TITLE
Fix Makefile compilation

### PR DESCRIPTION
**Pull request by anakojm**

### CODE REVIEW

**Comment by donniebreve** [comment]
Nice catch :+1:

**Review by donniebreve — APPROVED** [review]

**Comment by auouymous** [comment]
The binary should be linked with an `$(ldflags)` variable, not `$(cflags)`. Then `-pthread` can be moved from `cflags` to `ldflags`.

**Comment by donniebreve** [comment]
Thanks for the input. It's changed in https://github.com/donniebreve/touchcursor-linux/commit/a466e5533c027d50c2223637aeec4f85aad4932e.

**Comment by auouymous** [comment]
`cflags` shouldn't be passed when linking the binary.

```patch
-        $(cc) $(objects) $(cflags) $(ldflags) -o $@
+        $(cc) $(objects) $(ldflags) -o $@
```

**Comment by donniebreve** [comment]
Changed in https://github.com/donniebreve/touchcursor-linux/commit/106b0105c195861f936abf0510ac381cb5658743.

It's a little hard to find these comments on closed PRs. I would appreciate if you opened an issue and referenced the PR in question.

**Pull request merged**
